/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface AppHome {

    }

    interface AppJoin {

    }

    interface AppLogin {

    }

    interface AppRoot {

    }
  }


    interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

    var HTMLAppHomeElement: {
      prototype: HTMLAppHomeElement;
      new (): HTMLAppHomeElement;
    };
    

    interface HTMLAppJoinElement extends StencilComponents.AppJoin, HTMLStencilElement {}

    var HTMLAppJoinElement: {
      prototype: HTMLAppJoinElement;
      new (): HTMLAppJoinElement;
    };
    

    interface HTMLAppLoginElement extends StencilComponents.AppLogin, HTMLStencilElement {}

    var HTMLAppLoginElement: {
      prototype: HTMLAppLoginElement;
      new (): HTMLAppLoginElement;
    };
    

    interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

    var HTMLAppRootElement: {
      prototype: HTMLAppRootElement;
      new (): HTMLAppRootElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'app-home': JSXElements.AppHomeAttributes;
    'app-join': JSXElements.AppJoinAttributes;
    'app-login': JSXElements.AppLoginAttributes;
    'app-root': JSXElements.AppRootAttributes;
    }
  }

  namespace JSXElements {

    export interface AppHomeAttributes extends HTMLAttributes {

    }

    export interface AppJoinAttributes extends HTMLAttributes {

    }

    export interface AppLoginAttributes extends HTMLAttributes {

    }

    export interface AppRootAttributes extends HTMLAttributes {

    }
  }

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-join': HTMLAppJoinElement
    'app-login': HTMLAppLoginElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-join': HTMLAppJoinElement;
    'app-login': HTMLAppLoginElement;
    'app-root': HTMLAppRootElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

