/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface AppDashboard {

    }

    interface AppForbidden {

    }

    interface AppHome {

    }

    interface AppJoin {

    }

    interface AppLogin {

    }

    interface AppRoot {

    }

    interface AppButton {
      'contained': boolean;
      'disabled': boolean;
      'link': string;
      'secondary': boolean;
      'type': string;
    }

    interface AppHeader {

    }

    interface AppInput {
      'disabled': boolean;
      'id': string;
      'label': string;
      'name': string;
      'type': string;
    }

    interface StencilRouteProtected {
      'component': string;
      'url': string;
    }
  }


    interface HTMLAppDashboardElement extends StencilComponents.AppDashboard, HTMLStencilElement {}

    var HTMLAppDashboardElement: {
      prototype: HTMLAppDashboardElement;
      new (): HTMLAppDashboardElement;
    };
    

    interface HTMLAppForbiddenElement extends StencilComponents.AppForbidden, HTMLStencilElement {}

    var HTMLAppForbiddenElement: {
      prototype: HTMLAppForbiddenElement;
      new (): HTMLAppForbiddenElement;
    };
    

    interface HTMLAppHomeElement extends StencilComponents.AppHome, HTMLStencilElement {}

    var HTMLAppHomeElement: {
      prototype: HTMLAppHomeElement;
      new (): HTMLAppHomeElement;
    };
    

    interface HTMLAppJoinElement extends StencilComponents.AppJoin, HTMLStencilElement {}

    var HTMLAppJoinElement: {
      prototype: HTMLAppJoinElement;
      new (): HTMLAppJoinElement;
    };
    

    interface HTMLAppLoginElement extends StencilComponents.AppLogin, HTMLStencilElement {}

    var HTMLAppLoginElement: {
      prototype: HTMLAppLoginElement;
      new (): HTMLAppLoginElement;
    };
    

    interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

    var HTMLAppRootElement: {
      prototype: HTMLAppRootElement;
      new (): HTMLAppRootElement;
    };
    

    interface HTMLAppButtonElement extends StencilComponents.AppButton, HTMLStencilElement {}

    var HTMLAppButtonElement: {
      prototype: HTMLAppButtonElement;
      new (): HTMLAppButtonElement;
    };
    

    interface HTMLAppHeaderElement extends StencilComponents.AppHeader, HTMLStencilElement {}

    var HTMLAppHeaderElement: {
      prototype: HTMLAppHeaderElement;
      new (): HTMLAppHeaderElement;
    };
    

    interface HTMLAppInputElement extends StencilComponents.AppInput, HTMLStencilElement {}

    var HTMLAppInputElement: {
      prototype: HTMLAppInputElement;
      new (): HTMLAppInputElement;
    };
    

    interface HTMLStencilRouteProtectedElement extends StencilComponents.StencilRouteProtected, HTMLStencilElement {}

    var HTMLStencilRouteProtectedElement: {
      prototype: HTMLStencilRouteProtectedElement;
      new (): HTMLStencilRouteProtectedElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'app-dashboard': JSXElements.AppDashboardAttributes;
    'app-forbidden': JSXElements.AppForbiddenAttributes;
    'app-home': JSXElements.AppHomeAttributes;
    'app-join': JSXElements.AppJoinAttributes;
    'app-login': JSXElements.AppLoginAttributes;
    'app-root': JSXElements.AppRootAttributes;
    'app-button': JSXElements.AppButtonAttributes;
    'app-header': JSXElements.AppHeaderAttributes;
    'app-input': JSXElements.AppInputAttributes;
    'stencil-route-protected': JSXElements.StencilRouteProtectedAttributes;
    }
  }

  namespace JSXElements {

    export interface AppDashboardAttributes extends HTMLAttributes {

    }

    export interface AppForbiddenAttributes extends HTMLAttributes {

    }

    export interface AppHomeAttributes extends HTMLAttributes {

    }

    export interface AppJoinAttributes extends HTMLAttributes {

    }

    export interface AppLoginAttributes extends HTMLAttributes {

    }

    export interface AppRootAttributes extends HTMLAttributes {

    }

    export interface AppButtonAttributes extends HTMLAttributes {
      'contained'?: boolean;
      'disabled'?: boolean;
      'link'?: string;
      'secondary'?: boolean;
      'type'?: string;
    }

    export interface AppHeaderAttributes extends HTMLAttributes {

    }

    export interface AppInputAttributes extends HTMLAttributes {
      'disabled'?: boolean;
      'id'?: string;
      'label'?: string;
      'name'?: string;
      'type'?: string;
    }

    export interface StencilRouteProtectedAttributes extends HTMLAttributes {
      'component'?: string;
      'url'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'app-dashboard': HTMLAppDashboardElement
    'app-forbidden': HTMLAppForbiddenElement
    'app-home': HTMLAppHomeElement
    'app-join': HTMLAppJoinElement
    'app-login': HTMLAppLoginElement
    'app-root': HTMLAppRootElement
    'app-button': HTMLAppButtonElement
    'app-header': HTMLAppHeaderElement
    'app-input': HTMLAppInputElement
    'stencil-route-protected': HTMLStencilRouteProtectedElement
  }

  interface ElementTagNameMap {
    'app-dashboard': HTMLAppDashboardElement;
    'app-forbidden': HTMLAppForbiddenElement;
    'app-home': HTMLAppHomeElement;
    'app-join': HTMLAppJoinElement;
    'app-login': HTMLAppLoginElement;
    'app-root': HTMLAppRootElement;
    'app-button': HTMLAppButtonElement;
    'app-header': HTMLAppHeaderElement;
    'app-input': HTMLAppInputElement;
    'stencil-route-protected': HTMLStencilRouteProtectedElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

